### ISSUE TITLE
Which part in RISC-V GNU compiler toolchain do you modify to expose instructions to applications?

### ISSUE THREAD

**Issue by Z-KN** [CMU-SAFARI/PiDRAM#1]
Your work is awesome and vast! But at the same time, I find it hard to quickly identify which part you modify on RISC-V GNU compiler, to identify the CLFLUSH instruction to applications, as suggested in the paper. Could please help me point it out?

**Comment by PKUZHOU** [comment]
I have the similar question.  I am interested in how to implement CLFLUSH in Rocketchip. Have you figured it out?

**Comment by PKUZHOU** [comment]
It seems that PiDRAM does not include L2 cache and uses the FLUSH command, which flushes data in L1dcache as CLFLUSH.

**Comment by olgunataberk** [comment]
Hi all. Thanks for your nice comments! This answer may have gaps (trying to revive my experience) but I will come back to close those if necessary:

We followed [this useful guide](https://hsandid.github.io/posts/risc-v-custom-instruction/) in adding new instructions in the RISC-V compiler. As described in the guide, we made some modifications in [this file](https://github.com/CMU-SAFARI/PiDRAM/blob/master/fpga-zynq/rocket-chip/riscv-tools/riscv-opcodes/opcodes#L71), [this file](https://github.com/CMU-SAFARI/PiDRAM/blob/master/fpga-zynq/rocket-chip/riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/opcodes/riscv-opc.c#L283), and [this file](https://github.com/CMU-SAFARI/PiDRAM/blob/master/fpga-zynq/rocket-chip/riscv-tools/riscv-gnu-toolchain/riscv-binutils-gdb/include/opcode/riscv-opc.h#L144). After those modifications, we simply compile the toolchain.  

The logic responsible for executing flush instructions is in the L1 cache controller in [NBDCache.scala](https://github.com/CMU-SAFARI/PiDRAM/blob/master/fpga-zynq/rocket-chip/src/main/scala/rocket/NBDcache.scala). The RISC-V systems in PiDRAM's prototype does not implement an L2 cache. 

Assuming PKUZHOU is asking how to implement CLFLUSH in the upstream rocketchip repository, I would start by looking at the differences in PiDRAM's NBDCache and the upstream's NBDCache definitions (hopefully the differences are still mostly due to our changes), and then try to incorporate our flush logic into the upstream's NBDCache logic. Finally, if you implement a new instruction to expose the cache line flush operations to the program developer (like how we did), you need to ensure that the core sets the correct control signal (M_FLUSH) in the decoded micro-op when it decodes the new instruction (our new instruction's encoding ensures via [this line in Consts.scala](https://github.com/CMU-SAFARI/PiDRAM/blob/master/fpga-zynq/rocket-chip/src/main/scala/rocket/Consts.scala#L83) that the correct control signal is set).

**Comment by Z-KN** [comment]
Thank you very much!

**Comment by CollectAllUgly** [comment]
Excuse me, in the architecture of PiDRAM, the ddr3 of the entity is used as the data throughput container, why do we use the method of counting the time series in the controller, so that the result contains both the time series counting delay of PL and the real delay of the hardware in DDR3, so that the delay is doubled, is it  reasonable?
